[tool.poetry]
name = "georgia-frontend"
version = "3.4.3.13"
description = "georgia frontend"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8"

# pandas = 2
dash = 2.9.0



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
