[tool.poetry]
name = "georgia-frontend"
version = "3.4.3.16"
description = "georgia frontend"
authors = ["Marcelo Amorelli <marcelo.amorelli@upetrading.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8.15"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
